import os

#os.system("MeasureScale --configFile /sps/atlas/a/aguerguichon/Calibration/PreRec/Config/DataOff_13TeV_TEST.boost --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_0.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_1.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_2.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_3.root --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_0.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_1.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_2.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_3.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_4.root --outFileName /sps/atlas/a/aguerguichon/Calibration/Test/Scales/DataOff_13TeV_TEST.root")  


#os.system("MeasureScale --configFile /sps/atlas/a/aguerguichon/Calibration/PreRec/Config/DataOff_13TeV_TEST.boost --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_0.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_1.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_2.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_3.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_4.root --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_0.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_1.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_2.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_3.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_4.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_5.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_6.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_7.root --outFileName /sps/atlas/a/aguerguichon/Calibration/Test/Scales/DataOff_13TeV_TEST.root")  


os.system("MeasureScale --configFile /sps/atlas/a/aguerguichon/Calibration/PreRec/Config/DataOff_13TeV_TEST_c.boost --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_0.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_1.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_2.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_3.root  --dataFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/Data16_13TeV_Zee_Lkh1/Data16_13TeV_Zee_Lkh1_4.root --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_0.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_1.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_2.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_3.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_4.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_5.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_6.root  --MCFileName /sps/atlas/a/aguerguichon/Calibration/DataxAOD/MC15c_13TeV_Zee_Lkh1/MC15c_13TeV_Zee_Lkh1_7.root --outFileName /sps/atlas/a/aguerguichon/Calibration/Test/Scales/DataOff_13TeV_TEST_c.root --correctAlphaHistName measScale_alpha --correctAlphaFileName /sps/atlas/a/aguerguichon/Calibration/Test/Scales/DataOff_13TeV_TEST.root")  







#os.system("MeasureScale --configFile DataOff_13TeV_TEST_c.boost --dataFileName Data16_13TeV_Zee_Lkh1_0.root  --dataFileName Data16_13TeV_Zee_Lkh1_1.root  --dataFileName Data16_13TeV_Zee_Lkh1_2.root  --dataFileName Data16_13TeV_Zee_Lkh1_3.root  --dataFileName Data16_13TeV_Zee_Lkh1_4.root --MCFileName MC15c_13TeV_Zee_Lkh1_0.root  --MCFileName MC15c_13TeV_Zee_Lkh1_1.root  --MCFileName MC15c_13TeV_Zee_Lkh1_2.root  --MCFileName MC15c_13TeV_Zee_Lkh1_3.root  --MCFileName MC15c_13TeV_Zee_Lkh1_4.root  --MCFileName MC15c_13TeV_Zee_Lkh1_5.root  --MCFileName MC15c_13TeV_Zee_Lkh1_6.root  --MCFileName MC15c_13TeV_Zee_Lkh1_7.root --outFileName DataOff_13TeV_TEST_c.root  --correctAlphaHistName measScale_alpha --correctAlphaFileName DataOff_13TeV_TEST.root") 

